export const GET_ALL_PRODUCT = `GET_ALL_PRODUCT`;
export const GET_ALL_PRODUCT_SUCCESS = `GET_ALL_PRODUCT_SUCCESS`;
export const GET_ALL_PRODUCT_FAIL = `GET_ALL_PRODUCT_FAIL`;


export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART" ;


export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'


export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const  GET_PROFILE =" GET_PROFILE"
export const GET_PROFILE_SUCCESS ="GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL="GET_PROFILE_FAIL"

export const  GET_CART_ITEMS =" GET_CART_ITEMS"
export const GET_CART_ITEMS_SUCCESS ="GET_CART_ITEMS_SUCCESS"
export const GET_CART_ITEMS_FAIL="GET_CART_ITEMS_FAIL"

export const ADD_CART_ITEM = "ADD_CART_ITEM"